ActionInputBindings:
  - Name: Jump
    InputType: Keyboard
    Input: Space
  - Name: Jump_Gamepad
    InputType: Gamepad
    Input: A
  - Name: Run
    InputType: Keyboard
    Input: LeftShift
  - Name: Run
    InputType: Gamepad
    Input: RightBumper
  - Name: Dash
    InputType: Keyboard
    Input: V
  - Name: Dash
    InputType: Gamepad
    Input: Y
  - Name: Teleport
    InputType: Keyboard
    Input: R
  - Name: Teleport
    InputType: Gamepad
    Input: B
  - Name: Interact
    InputType: Keyboard
    Input: E
  - Name: Interact
    InputType: Gamepad
    Input: X
  - Name: Exit
    InputType: Keyboard
    Input: Escape
  - Name: Exit
    InputType: Gamepad
    Input: Start
AxisInputBindings:
  - Name: Player_MoveForward
    InputType: Keyboard
    Inputs:
      - Input: W
        Value: 1.0
      - Input: S
        Value: -1.0
  - Name: Player_MoveRight
    InputType: Keyboard
    Inputs:
      - Input: D
        Value: 1.0
      - Input: A
        Value: -1.0
  - Name: Player_Turn
    InputType: Mouse
    Inputs:
      - Input: MouseX
        Value: 1.0
  - Name: Player_LookUp
    InputType: Mouse
    Inputs:
      - Input: MouseY
        Value: 1.0
  - Name: Player_MoveForward
    InputType: Gamepad
    Inputs:
      - Input: LeftY
        Value: -1.0
  - Name: Player_MoveRight
    InputType: Gamepad
    Inputs:
      - Input: LeftX
        Value: 1.0
  - Name: Player_Turn
    InputType: Gamepad
    Inputs:
      - Input: RightX
        Value: 1.0
  - Name: Player_LookUp
    InputType: Gamepad
    Inputs:
      - Input: RightY
        Value: 1.0